version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: jupyter
    ports: 
      - "8888:8888"
    working_dir: '/app'
    volumes:
      - ./app:/app/
    command: "jupyter notebook --ip='0.0.0.0' --port 8888 --no-browser --allow-root --NotebookApp.token=''"

  python:
    build:
      context: .
      dockerfile: Dockerfile
      target: python
    ports:
      - "9999:9999"
    working_dir: '/app'
    volumes:
      - ./app:/app/
    tty: "true"